const {chromium}=require('playwright');(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});const p=await b.newPage({viewport:{width:1280,height:720}});
const errs=[];p.on('pageerror',e=>errs.push(e.message));await p.goto('http://localhost:8765/index.html');await p.waitForTimeout(5000);
await p.evaluate(()=>{S.test=true;TEST['Mindent megvesz']();TEST['Próbaterem']();});await p.waitForTimeout(1500);
const [skid,foe,foesk]=process.argv.slice(2);
await p.evaluate(([skid,foe,foesk])=>{S.enemies.forEach(e=>e.alive=false);const mk=(t,i)=>{const e=mkEnemy(t,SLOTS[2][i][0],SLOTS[2][i][1],30);e.hp=e.maxHp=99999;S.enemies.push(e);return e;};const e=mk(foe||'slime',0);mk('slime',1);
 for(const h of S.heroes){h.hp=h.maxHp=99999;h.alive=true;h.st={};}S.speed=.5;let h,sk;const need=t=>{let x=S.heroes.find(q=>q.type===t);if(!x){x=(S.roster||[]).find(q=>q.type===t)||mkHero(t);const r=S.heroes[S.heroes.length-1];x.x=r.x;x.y=r.y;x.alive=true;x.hp=x.maxHp=99999;x.st={};S.heroes[S.heroes.length-1]=x;}return x;};if(skid.startsWith('L_')){const ty=skid.slice(2);h=need(ty);if(ty==='witch')h._cerb=true;sk=LIMITS[ty];}else{const ty=Object.keys(SHOP_SKILLS).find(t=>SHOP_SKILLS[t].some(q=>q[0]===skid))||Object.keys(HERO_DEF).find(t=>(HERO_DEF[t].skills||[]).includes(skid));h=ty?need(ty):S.heroes[0];sk=SK[skid];}const tg=sk.tgt==='enemies'?S.enemies.filter(e=>e.alive):sk.tgt==='allies'?S.heroes.filter(h=>h.alive):[e];
 perform(h,{type:'skill',sk,targets:tg}).then(()=>{if(foesk)setTimeout(()=>useEnemySkill(e,ESK[foesk],S.heroes[0]),300);});},[skid,foe,foesk]);
const fs=[];for(let i=0;i<20;i++){await p.waitForTimeout(+process.env.INT||350);const f=`hs/H_${skid}_${foesk||""}_${i}.png`;await p.screenshot({path:f,clip:{x:0,y:0,width:640,height:365}});fs.push(f);}
require('child_process').execSync(`montage ${fs.join(' ')} -tile 4x -geometry 400x228+1+1 h_${skid}${foesk?'_'+foesk:''}.jpg`);console.log('hibák',errs.join('|')||'nincs');await b.close();})();
