import json,os,glob
D='rv11/review/'
R={ # id: (reply, test title, how, expect, area)
't-h01':("Visszaállítottam: felragyog, minden hős elé pajzs kerül, aztán középen egy nagy marad. Egységes szabály: amíg a nagy pajzs áll, bármelyik hőst éri támadás, kivédi és visszaveri – annyiszor, ahány hős kapta.","Fénypajzs: régi megjelenés + mindig visszaver","Próbaterem: Lili Fénypajzsa, aztán kérj ellenséges támadást (több különbözőt is).","Sok kis pajzs, majd egy nagy középen; minden ütés visszapattan a támadóra, egyik hős sem sérül.","Képességek"),
't-h03':("Nincs tűzoszlop: Espresszó kitátja a száját, parázs gyűlik benne, és valódi lángnyelvekből álló csóva ömlik a szájából.","Espresszó idézés: tűz a szájból","Idézés: Espresszó, a sárkány.","Lángcsóva a szájából, tűzoszlop nincs.","Idézések"),
't-h04':("Kamilla a saját legyezőjét lendíti meg: kinyílik, nagyobb lesz, szellemképekkel csap le, utána jön a széllökés.","Kamilla idézés: legyezőlendítés","Idézés: Kamilla.","A kezében lévő legyezője nő meg és nagy ívben lecsap, utána széllökés.","Idézések"),
't-h05':("A Főnix már nem ad védelmet, csak feltámaszt és teljesen gyógyít.","Főnix: nincs védelem","Idézés: Főnix.","Feltámasztás + teljes gyógyítás, „Védelem+” nem jelenik meg.","Idézések"),
't-h06':("Hatalmas, gomolygó lila spórafüst tör ki a kalapjából, és beborítja az ellenségeket (valódi füsttextúra).","Gomba-Király: nagy lila füst","Idézés: Gomba-Király.","Nagy, valósághű lila füstfelhő az ellenségeken.","Idézések"),
't-h07':("Oolong kitátja a száját, és onnan ömlik a forró gőz; a célpontokon gőzfelhő.","Oolong idézés: gőz a szájból","Idézés: Öreg Oolong.","A gőz a sárkány szájából jön.","Idézések"),
't-h08':("Új méhraj: 130 rajzolt, szőrös méh szétterül, újra meg újra lecsap (rohamokban), zümmögéssel.","Mézkirálynő idézés: nagy, agresszív raj","Idézés: Mézkirálynő.","Sok, valósághű méh szétszóródik és többször rácsap az ellenségekre.","Idézések"),
't-h13':("A por most az égből hullik le az egész csapatra; a csengő hangot kivettem.","Tündérpor: fentről hulló por","Lili: Tündérpor.","Egy porgömb felszáll, aztán fentről hullik a por mindenkire; nincs csengőhang.","Képességek"),
't-h18':("Sarló alakú hold; a bicikli-csengő hang az egész játékból kikerült (helyette lágy varázssuhogás).","Álomcsillagok: sarló hold, nincs csengő","Lili: Álomcsillagok.","Sarlós hold; sehol nincs csengőhang.","Képességek"),
'f-bamboo-bamboojab':("A bambuszőr a saját lándzsáját hajítja el a kezéből; utána új bambusz nő a kezébe.","Bambuszőr: lándzsadobás","Ellenfél: Bambuszőr – Bambuszdöfés.","A kezében lévő lándzsa repül el és fúródik a hősbe.","Ellenfelek"),
'f-bamboo-bamboowall':("Új támadás: Bambuszketrec – alulról bambuszok nőnek ki egy hős körül, és 1 körre bezárják (kábulat), a ketrec addig látszik.","Bambuszketrec","Ellenfél: Bambuszőr – Bambuszketrec.","Bambuszok nőnek fel a hős körül, ketrec 1 körig, a hős kimarad.","Ellenfelek"),
'f-beast-frenzy':("Felvonyít (hanghullám), és 6 árnypéldánya végigsuhan a hősökön, karmolásnyomokkal.","Vadállat: Tombolás","Ellenfél: Vadállat – Tombolás.","Vonyítás, majd 5-6 árnymásolat suhan végig minden hősön.","Ellenfelek"),
'f-bee-honeyshot':("A mézpálcáról nagy, csöpögő mézgömb lő ki, ami beborítja a hőst (csorgó méz rajta).","Méhecske: Mézlövet","Ellenfél: Méhecske – Mézlövet.","Nagy mézgömb, a hősön lecsorgó méz.","Ellenfelek"),
'f-bee-sting':("Hátrál, lendületet vesz, szellemképekkel becsapódik; zöldes méregcsöppek a találatnál.","Méhecske: Fullánk","Ellenfél: Méhecske – Fullánk.","Lendületes roham és fullánkszúrás.","Ellenfelek"),
'f-candysheep-sweetdream':("Rózsaszín vattacukor-felhők gördülnek a hősökre, bennük lebegő cukorkák.","Vattacukor-bárány: Édes álom","Ellenfél: Vattacukor-bárány – Édes álom.","Vattacukorfelhők és cukorkák a hősökön.","Ellenfelek"),
'f-cannon-shot':("Torkolattűz és füst a csőből, hátrarúgás, igazi vasgolyó füstcsíkkal, nagy robbanás törmelékkel.","Ágyú: lövés","Ellenfél: Óramű ágyú – Ágyúlövés.","Látványos lövés és robbanás.","Ellenfelek"),
'f-cannon-broadside':("Sorban minden hősre külön lövés, mindegyik nagy robbanással.","Ágyú: Sortűz","Ellenfél: Óramű ágyú – Sortűz (főellenség).","Több látványos lövés egymás után.","Ellenfelek"),
'f-ccube-chaosbolt':("A kocka képe már nem változik lövés közben; a lövedék szivárványos hanghullám-robbanással csapódik be.","Káoszkocka: nem vált képet","Ellenfél: Káoszkocka – Káoszlövedék.","A kocka ugyanaz marad lövés közben.","Ellenfelek"),
'f-cgolem-crystalpunch':("A gólem saját ökle kristálytüskéket növeszt, előrecsapódik, nagy becsapódás szilánkokkal.","Kristálygólem: Kristályököl","Ellenfél: Kristálygólem – Kristályököl.","Az ökle kristályossá válik, nagy becsapódás.","Ellenfelek"),
'f-cgolem-shardspray':("Valódi, csiszolt kristályszilánkok zuhannak és pattannak szét (csillagok helyett). A gólem megkapta az idézése képességét is: Tükörpajzs.","Kristálygólem: szilánkok + Tükörpajzs","Ellenfél: Kristálygólem – Szilánkeső, majd Tükörpajzs.","Igazi szilánkok; Tükörpajzs: kék pajzs az ellenfelek előtt, visszaver.","Ellenfelek"),
'f-cupsoldier-spoonstab':("A csészekatona a saját kanállándzsáját döfi háromszor.","Csészekatona: Kanáldöfés","Ellenfél: Csészekatona – Kanáldöfés.","A kezében lévő lándzsa döf, 3 szúrás.","Ellenfelek"),
'f-cupsoldier-teasplash':("A csészéből hullámzó, cseppes, gőzölgő teasugár csap ki.","Csészekatona: Teafröccs","Ellenfél: Csészekatona – Teafröccs.","Valódi folyadéksugár, fröccsenés, gőz.","Ellenfelek"),
'f-doll-crackshard':("Nincs szívecske: a baba nem vált a szíves támadóképére.","Porcelánbaba: Szilánkszórás szív nélkül","Ellenfél: Porcelánbaba – Szilánkszórás.","Szilánkok, szívek nincsenek.","Ellenfelek"),
'f-doll-dollkiss':("Csókot dob: rúzsos ajkak repülnek, a csókjel megreped, sötét átokfüst.","Porcelánbaba: Porcelán csók","Ellenfél: Porcelánbaba – Porcelán csók.","Repülő ajkak, repedő csókjel.","Ellenfelek"),
'f-espresso-doublebreath':("Ugyanaz, mint az idézésnél: lángcsóva a szájából (hamu-alakban gőzös-hamus).","Espresszó: Duplán pörkölt lehelet","Ellenfél: Espresszó – Duplán pörkölt lehelet.","Lángnyelvek a szájból.","Ellenfelek"),
'f-espresso-tailswipe':("A sárkány a SAJÁT farkát lendíti: odafut, megfordul, a farka felemelkedik és lecsap.","Espresszó: Farokcsapás saját farokkal","Ellenfél: Espresszó – Farokcsapás.","A képen lévő farok mozog, nem külön rajz.","Ellenfelek"),
'f-ghost-chill':("Kék jeges lehelet, a hős 1 körre lefagy (jég elem); a hányásszerű hangot kivettem, jeges hang szól.","Kísértet: Hideg érintés","Ellenfél: Kísértet – Hideg érintés.","Kék lehelet, jégkristályok, 1 kör fagyás, jó hang.","Ellenfelek"),
'f-ghost-wail':("Nincs hullám: a sikoly egy hanggömböt lő a hősök közé, ott nagy hanghullám-robbanás.","Kísértet: Jajveszékelés","Ellenfél: Kísértet – Jajveszékelés.","Hanghullám-robbanás a hősök között.","Ellenfelek"),
'f-gingerman-candycane':("A saját cukorpálcáját lendíti két kézzel, nagy ívben.","Mézeskalács: Cukorpálca-ütés","Ellenfél: Mézeskalács-bandita – Cukorpálca-ütés.","A kezében lévő pálca mozog.","Ellenfelek"),
'f-gingerman-icingbomb':("Habcsók-bomba repül a hősök fölé, felrobban, cukormáz-zuhatag és máz a fejükön.","Mézeskalács: Cukormáz-bomba","Ellenfél: Mézeskalács-bandita – Cukormáz-bomba.","Bomba, robbanás, mázeső.","Ellenfelek"),
'f-gingerman-snatch':("Ha van tőr vagy tűzbomba, azt lopja el (fogy a készletből), és rögtön a hősökre dobja.","Mézeskalács: lopott fegyver","Csatában legyen tőr/tűzbomba a táskában; Mézeskalács-bandita – Elcsenés.","Ellopja és visszadobja.","Ellenfelek"),
'f-gknight-darkwave':("Nem vizes: fekete-lila árnyfüst és szikrák söpörnek a földön, karomnyomokkal.","Sötét lovag: Sötét hullám","Ellenfél: Sötét lovag – Sötét hullám.","Füstös, sötét hullám, nem víz.","Ellenfelek"),
'f-harp-lullaby':("Saját altatódal: a hárfa húrjai rezegnek és ragyognak, színes hangjegyek szállnak a hősökre.","Hárfa: Altatódal","Ellenfél: Hárfa – Altatódal.","Rezgő húrok, hangjegyek.","Ellenfelek"),
'f-harp-stringsnap':("Három húr pattan ki villámló ostorként, a hőst áramütés éri.","Hárfa: Húrpattanás","Ellenfél: Hárfa – Húrpattanás.","Húr-ostorok, áramütés.","Ellenfelek"),
'f-iceelem-icicles':("Dérfelhőben hatalmas jégcsapok nőnek a hősök fölé, lezuhannak és szilánkokra robbannak.","Jégelementál: Jégcsapok","Ellenfél: Jégelementál – Jégcsapok.","Nagy jégcsapok, robbanás.","Ellenfelek"),
'f-jamdjinn-jamwave':("Visszaállítottam a korábbi változatot.","Lekvárdzsinn: régi Lekvárhullám","Ellenfél: Lekvárdzsinn – Lekvárhullám.","A korábbi hullám.","Ellenfelek"),
'f-jamdjinn-stickyhand':("A dzsinn SAJÁT karja nyúlik ki gumiszerűen, a keze rámarkol a hősre.","Lekvárdzsinn: saját karja nyúlik","Ellenfél: Lekvárdzsinn – Ragacsos kéz.","A képen lévő kar és kéz nyúlik ki.","Ellenfelek"),
'f-jamdjinn-wish':("Látható hatás: arany lámpás jelenik meg, minden ellenség kap egy csillagot: 1 körig Erő+ és 15% gyógyulás.","Lekvárdzsinn: Kívánság","Ellenfél: Lekvárdzsinn – Kívánság.","Lámpás, csillagok, „KÍVÁNSÁG: ERŐ+” felirat.","Ellenfelek"),
'f-kamilla-fanhurricane':("A saját legyezőjét nagyra nyitva lendíti, tealevél-forgószél söpör végig.","Kamilla: Legyezőhurrikán","Ellenfél: Kamilla – Legyezőhurrikán.","A kezében lévő legyező lendül.","Ellenfelek"),
'f-kamilla-lullaby':("Kamillaszirmok és hangjegyek úsznak a hősökre, aranyló álomköd.","Kamilla: Altatófurulya","Ellenfél: Kamilla – Altatófurulya.","Szirmok, hangjegyek, köd.","Ellenfelek"),
'f-kamilla-teaceremony':("Lebegő teáskanna aranyló teát tölt egy csészébe, a csésze forró sugárban a hősre zúdítja.","Kamilla: Teaszertartás","Ellenfél: Kamilla – Teaszertartás.","Kanna tölt, csésze rázúdítja.","Ellenfelek"),
'f-koffgolem-doubleshot':("Két óriási, habos kávésugár.","Koffein-gólem: Dupla presszó","Ellenfél: Koffein-gólem – Dupla presszó.","Két vastag kávésugár, hab, fröccsenés.","Ellenfelek"),
'f-lantern-lanternfire':("Kék lángcsóva gyűlik a szájában, nagy kék tűzgolyóként csapódik be.","Lampion: Lampionláng","Ellenfél: Lampion – Lampionláng.","Kék tűzgolyó, robbanás.","Ellenfelek"),
'f-lantern-willolight':("Lidércrobbanás: felragyog, odasuhan, felrobban – és a lampion végleg meghal.","Lampion: Lidércrobbanás","Ellenfél: Lampion – Lidércrobbanás.","Ragyogás, roham, robbanás, a lampion eltűnik.","Ellenfelek"),
'f-mage-darkwave':("Nem vizes: árnyfüst-hullám (ugyanaz, mint a sötét lovagnál).","Varázsló: Sötét hullám","Ellenfél: Varázsló – Sötét hullám.","Füstös árnyhullám.","Ellenfelek"),
'f-mandarin-inkcurse':("Óriás ecset fekete tusvonásokat fest a hősök elé, a tus rájuk csorog. A tükörmáz minden körben kiírja, mikor véd (és mikor nem).","Mandarin: Tusátok és pajzs","Ellenfél: Porcelán mandarin – Tusátok; nézd a kör eleji feliratot.","Ecsetvonások, csorgó tus; „TÜKÖRMÁZ…” felirat.","Ellenfelek"),
'f-monkey-cupthrow':("A kezében tartott csészét lendíti hátra, és onnan dobja el; a csésze szétreped, tea fröccsen.","Majom: Csészedobás","Ellenfél: Tealopó majom – Csészedobás.","A kezéből indul a csésze.","Ellenfelek"),
'f-monkey-snatch':("Ellopja a tőrt vagy a tűzbombát, és a hősökre dobja.","Majom: lopott fegyver","Legyen tőr/tűzbomba; Tealopó majom – Elcsenés.","Lopás és visszadobás.","Ellenfelek"),
'f-moth-dustwing':("Három hullámban csillogó, holdfényes hímporfelhő a szárnyakról.","Molylepke: Hímpor","Ellenfél: Molylepke – Hímpor.","Csillogó porhullámok.","Ellenfelek"),
'f-moth-moonbeam':("Csillagos ég, sarlós hold, belőle széles ezüst fénycsóva a hősre.","Molylepke: Holdsugár","Ellenfél: Molylepke – Holdsugár.","Sarló hold, fénycsóva.","Ellenfelek"),
'f-nightmare-dreadclaw':("Árnyfüstből kinyúló, nagy lila karmok háromszor tépnek.","Rémálom: Rémkarom","Ellenfél: Rémálom – Rémkarom.","Három nagy karmolás.","Ellenfelek"),
'f-nightmare-nightterror':("Sötétben vörös szemű árnypéldányok tömege rohan át a hősökön.","Rémálom: Rémálom","Ellenfél: Rémálom – Rémálom.","Vörös szemű árnyak rohama.","Ellenfelek"),
'f-oknight-moltenblade':("Tüzes: a kard izzik és lávát csöpög, lángoló vágásív.","Obszidián lovag: Olvadt kard","Ellenfél: Obszidián lovag – Olvadt kard.","Tüzes penge és ív.","Ellenfelek"),
'f-oknight-obswall':("Támadás lett: középen kitör egy lávás obszidiánfal, és rádől a hősökre.","Obszidián lovag: Obszidiánfal","Ellenfél: Obszidián lovag – Obszidiánfal.","Fal tör ki és ráborul a hősökre.","Ellenfelek"),
'f-oolong-dragonbite':("Oolong saját feje lódul előre a nyakát nyújtva, és ráharap.","Oolong: Sárkányharapás","Ellenfél: Öreg Oolong – Sárkányharapás.","A képen lévő fej harap.","Ellenfelek"),
'f-oolong-mistcoil':("Ködkígyó tekeredik a hős köré; elszívja a varázserejét (MP), és Oolong abból gyógyul.","Oolong: Ködgyűrű","Ellenfél: Öreg Oolong – Ködgyűrű.","Köd a hős körül, „-MP”, Oolong gyógyul.","Ellenfelek"),
'f-oolong-steambreath':("A gőz Oolong szájából ömlik (mint az idézésnél).","Oolong: Gőzlehelet","Ellenfél: Öreg Oolong – Gőzlehelet.","Gőz a szájból.","Ellenfelek"),
'f-pillowknight-featherstorm':("A saját párnáját hajítja fel, szétszakad, 120 tollból örvény kavarog a hősök körül.","Párnalovag: Tollvihar","Ellenfél: Párnalovag – Tollvihar.","Párna felrepül, tollörvény.","Ellenfelek"),
'f-pillowknight-pillowbash':("A saját párnáját megnövelve a feje fölül lecsapja, 40 toll repül.","Párnalovag: Párnacsapás","Ellenfél: Párnalovag – Párnacsapás.","Nagy párna lecsap, sok toll.","Ellenfelek"),
'f-potturtle-hotpour':("Vastag, gőzölgő teasugár ível a csőréből, tócsa a hős alatt.","Kannateknős: Forró öntés","Ellenfél: Kannateknős – Forró öntés.","Gőzölgő sugár, tócsa.","Ellenfelek"),
'f-queenbee-buzzstorm':("Ugyanaz a nagy, valósághű, agresszív méhraj, mint az idézésnél.","Mézkirálynő: Zümmögővihar","Ellenfél: Mézkirálynő – Zümmögővihar.","Nagy, szétszóródó raj.","Ellenfelek"),
'f-queenbee-honeyrain':("Funkció: a méz 1 körig sebezhetőbbé teszi a hősöket (Védelem−), és meggyógyítja a királynőt és a méheket. Mézfelhő, mézeső, csorgó méz.","Mézkirálynő: Mézeső","Ellenfél: Mézkirálynő – Mézeső.","Mézeső, „Védelem−”, a méhek gyógyulnak.","Ellenfelek"),
'f-queenbee-royalsting':("Sárga méreg: sárga csöppek, sárga felhő és fény.","Mézkirálynő: Királyi fullánk","Ellenfél: Mézkirálynő – Királyi fullánk.","Sárga méreg.","Ellenfelek"),
'f-rustking-gearthrow':("Új neve „Fogaskerékhullás”: fogaskerekek és csavarok zuhannak az égből egy hősre, pattognak.","Rozsdakirály: Fogaskerékhullás","Ellenfél: Rozsdakirály – Fogaskerékhullás.","Fogaskerekek és csavarok egy hősre.","Ellenfelek"),
'f-salamander-lavaspit':("Új neve „Tűzgolyó”: a szájában gyűlő tűzgolyó, robbanás.","Szalamandra: Tűzgolyó","Ellenfél: Lávaszalamandra – Tűzgolyó.","Tűzgolyó, nem láva.","Ellenfelek"),
'f-samovar-boilover':("Felforr, és forró víz meg gőz keveréke ömlik a hősökre (víz elem).","Szamovár: Kifutó forrás","Ellenfél: Szamovár-gólem – Kifutó forrás (3 kör után).","Víz és gőz együtt.","Ellenfelek"),
'f-samovar-scald':("Vastag forróvíz-sugár a csapjából, gőzölög, háromszor fröccsen.","Szamovár: Forrázás","Ellenfél: Szamovár-gólem – Forrázás.","Gőzölgő sugár a csapból.","Ellenfelek"),
'f-sandman-sandthrow':("Aranyló álomhomok-marék és csillogó porörvény a hős feje körül.","Homokember: Álomhomok","Ellenfél: Homokember – Álomhomok.","Homok, örvénylő csillogás.","Ellenfelek"),
'f-scorpion-caramelsting':("A skorpió SAJÁT farka csap le, karamell csöpög róla.","Skorpió: Karamellfullánk","Ellenfél: Karamellskorpió – Karamellfullánk.","A képen lévő farok mozog.","Ellenfelek"),
'f-scorpion-clawsnap':("A SAJÁT két ollója csattan össze kétszer.","Skorpió: Ollócsattanás","Ellenfél: Karamellskorpió – Ollócsattanás.","A képen lévő ollók mozognak.","Ellenfelek"),
'f-shfairy-shheal':("Új értelme: Árnyéklopás – életet szív egy hősből, és azzal a legsebesültebb árnytársát gyógyítja.","Árny-Lili: Árnyéklopás","Ellenfél: Árny-Lili (Morcus 2. fázis).","Sötét csáp a hősből, a társ gyógyul.","Ellenfelek"),
'f-shwizard-shinferno':("A második tűz helyett Árny-jégvihar (jég elem, fagyaszthat).","Árny-Zordon: Árny-jégvihar","Ellenfél: Árny-Zordon.","Lila jégvihar, nem tűz.","Ellenfelek"),
'f-skeleton-shieldbash':("A csontváz a SAJÁT kerek pajzsát rántja maga elé, azzal kólint; csillagok a hős feje körül.","Csontváz: Pajzscsapás","Ellenfél: Csontváz őr – Pajzscsapás.","A pajzs üt, nem kard.","Ellenfelek"),
'f-sleepless-dreamsteal':("Más, mint a bámulás: a hős álma buborékként kiszáll, a szem elnyeli, Álmatlan gyógyul, a hős elalszik.","Álmatlan: Álomlopás","Ellenfél: Álmatlan – Álomlopás.","Álombuborék repül a szembe.","Ellenfelek"),
'f-sugarcube-sugardust':("Megrázza magát, csillogó porcukor-hóvihar, porcukor a hősök fején.","Cukorkocka: Porcukorfelhő","Ellenfél: Cukorkocka – Porcukorfelhő.","Rázkódás, sűrű porcukorfelhő.","Ellenfelek"),
'f-tbat-screech':("Vastag, villódzó hanghullámok a szájából, a hősöket áram járja át; az idézés is ez lett.","Villámdenevér: Bénító sikoly (+idézés)","Ellenfél: Villámdenevér – Bénító sikoly; és idézés.","Hanghullámok, nincs égi villám.","Ellenfelek"),
'f-teaimp-leafcut':("Hat nagy, erezett tealevél kering körülötte, aztán spirálban belevág.","Teamanó: Levélvágás","Ellenfél: Tealevél-manó – Levélvágás.","Keringő levelek, vágások.","Ellenfelek"),
'f-teaimp-teadart':("Fúvócsővel kilőtt mérgezett tüske, beleáll a hősbe.","Teamanó: Teatüske","Ellenfél: Tealevél-manó – Teatüske.","Fúvócső, tüske a hősben.","Ellenfelek"),
'f-teaset-platestorm':("18 tányér kering körülötte, majd viharként zúdul a hősökre és összetörik.","Szerviz: Tányérvihar","Ellenfél: Az Ezerrészes Szerviz – Tányérvihar.","Keringő, majd lecsapó tányérok.","Ellenfelek"),
'f-teaset-potcrush':("Igazi porcelán teáskanna (kifolyó, fül, fedő, kék minta) zuhan a hősre.","Szerviz: Kannazúzás","Ellenfél: Szerviz – Kannazúzás.","Felismerhető teáskanna.","Ellenfelek"),
'f-teaset-teaflood':("Lecseréltem: Porcelánroham – a csészekatonák serege végigrohan a hősökön (mint az idézés).","Szerviz: Porcelánroham","Ellenfél: Szerviz – Porcelánroham.","Csészekatona-roham.","Ellenfelek"),
'f-teddy-bearhug':("A Maci SAJÁT karjaival öleli át a hőst és háromszor megszorongatja.","Maci: Macióölelés","Ellenfél: Mackóőr – Macióölelés.","A képen lévő karok ölelnek.","Ellenfelek"),
'f-teddy-growl':("Funkció: a hősök megrémülnek (1 körig Védelem−), a Maci 1 körig Erő+.","Maci: Morgás","Ellenfél: Mackóőr – Morgás.","„MEGRÉMÜLT!”, Maci „ERŐ+”.","Ellenfelek"),
'f-tongs-pinch':("A rák SAJÁT csipeszének két szára csukódik össze, megemeli és szorongatja a hőst.","Rák: Csípés","Ellenfél: Cukorfogó rák – Csípés.","A képen lévő csipesz mozog.","Ellenfelek"),
'f-vase-vaseguard':("Halvány, a váza mintájával festett vázadarab-fal áll fel előtte, amíg a védelem tart.","Vázagólem: Mázpáncél","Ellenfél: Vázagólem – Mázpáncél.","Mintás, halvány fal előtte.","Ellenfelek"),
'f-zombie-rottenbun':("Jól látható, penészes kifli repül a kezéből, büdös gázfelhő.","Zombi: Rothadt kifli","Ellenfél: Zombi pék – Rothadt kifli.","Kifli alakú, penészes.","Ellenfelek"),
}
extra=[("Csengő hang sehol","Játssz több gyógyító/fény képességet és idézést.","Sehol nincs bicikli-csengő vagy gong hang.","Hangok"),
("Valódi füst- és tűztextúrák","Nézz meg füstös/tüzes támadásokat (pl. gőz, robbanás).","A füst, gőz, tűz valósághű, nem kerek pöttyök.","Látvány"),
("Morcus új támadásai","4-4: Morcus.","Káoszkockák, Káoszvihar, Árnykarmok is előfordulnak.","Ellenfelek"),
("Tükörpajzs (Kristálygólem)","Ellenfél: Kristálygólem – Tükörpajzs, aztán üsd meg.","A támadás visszapattan.","Ellenfelek")]
ws=[];tests=[];o=1
for k,(rep,ti,how,exp,area) in R.items():
    f=D+k+'.json'
    assert os.path.exists(f),k
    p=f'wr/r_{k}.json';json.dump({'handled':True,'reply':rep},open(p,'w'),ensure_ascii=False)
    ws.append({'op':'update','collection':'review','doc_id':k,'file_path':os.path.abspath(p),'_v':None})
    tests.append((k.replace('f-','').replace('t-',''),ti,how,exp,area))
for i,(ti,how,exp,area) in enumerate(extra):tests.append(('x%02d'%i,ti,how,exp,area))
tw=[]
for i,(id_,ti,how,exp,area) in enumerate(tests):
    p=f'wr/t_{i}.json';json.dump({'area':area,'title':ti,'how':how,'expect':exp,'order':i+1},open(p,'w'),ensure_ascii=False)
    tw.append({'op':'set','collection':'tests','doc_id':'k'+'%03d'%(i+1),'file_path':os.path.abspath(p)})
json.dump({'reviews':list(R.keys()),'tw':tw},open('wr/plan.json','w'))
print(len(R),len(tw))
